### ISSUE TITLE
How to get labels for each input document?

### ISSUE THREAD

**Issue by ryanon4** [MrParosk/pyDenStream#1]
Firstly, i'm impressed by this package, however I notice a vital feature lacking which would assist in any future implementations:

I can't seem to identify an object or method for acessing the output labels given the input array of points?
In an sklearn type project, this would be through the fit_predict() function, or predict() function. However i'm unsure how to do this with pyDenStream. Could this be accessed through one of the internal _find_closest_cluster() or _request_clustering() methods (although this only returns labels of the micro-clusters?

**Comment by MrParosk** [comment]
Hi,

Sorry for the late reply, I have been quite busy lately.

Thanks for the feedback! I think it sounds like good additions to the library, I'll have a look at it.

**Comment by RicoMontulet** [comment]
Very interested in this, so +1 from me!

**Comment by MrParosk** [comment]
Could you describe how this would work? Do you want the clusters of the individual points? Or the micro clusters?
